const series = [
    {
        id: '0',
        title: 'Vikings',
        sinopse: 'A série é inspirada nas histórias de invasões, comércio e exploração dos Nórdicos da Escandinávia medieval. ... A série se passa no início da era viking, marcada pelo ataque de Lindisfarne, em 793.',
        imgURL: 'https://umpoucodeseries.files.wordpress.com/2016/06/vikings_season3_cast.jpg?w=1500&h=768&crop=1',
        status: 'watched',
        genre: ['Ação'],
    },
    {
        id: '1',
        title: 'Breaking Bad',
        sinopse: 'Walter White (Bryan Cranston) é um professor de química na casa dos 50 anos que trabalha em uma escola secundária no Novo México.',
        imgURL: 'https://www.meliuz.com.br/blog/wp-content/uploads/2013/09/jesse-pinkman-walter-white-breaking-bad.jpg',
        status: 'watched',
        genre: ['Drama', 'Suspense'],
    },
    {
        id: '2',
        title: 'How I Met Your Mother',
        sinopse: 'Em 2030, o arquiteto Ted Mosby (Josh Radnor) conta a história sobre como conheceu a mãe dos seus filhos. Ele volta no tempo para 2005, relembrando suas aventuras amorosas em Nova York e a busca pela mulher dos seus sonhos.',
        imgURL: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS_LahN6_7brPsOJvOMhfojbTV2H74Nlx8Ny_Y3pqSuG6tJAqGW',
        status: 'watched',
        genre: ['Comédia'],
    },
    {
        id: '0',
        title: 'Vikings',
        sinopse: 'A série é inspirada nas histórias de invasões, comércio e exploração dos Nórdicos da Escandinávia medieval. ... A série se passa no início da era viking, marcada pelo ataque de Lindisfarne, em 793.',
        imgURL: 'https://umpoucodeseries.files.wordpress.com/2016/06/vikings_season3_cast.jpg?w=1500&h=768&crop=1',
        status: 'watched',
        genre: ['Ação'],
    },
    {
        id: '0',
        title: 'Vikings',
        sinopse: 'A série é inspirada nas histórias de invasões, comércio e exploração dos Nórdicos da Escandinávia medieval. ... A série se passa no início da era viking, marcada pelo ataque de Lindisfarne, em 793.',
        imgURL: 'https://umpoucodeseries.files.wordpress.com/2016/06/vikings_season3_cast.jpg?w=1500&h=768&crop=1',
        status: 'watched',
        genre: ['Ação'],
    },
    {
        id: '0',
        title: 'Vikings',
        sinopse: 'A série é inspirada nas histórias de invasões, comércio e exploração dos Nórdicos da Escandinávia medieval. ... A série se passa no início da era viking, marcada pelo ataque de Lindisfarne, em 793.',
        imgURL: 'https://umpoucodeseries.files.wordpress.com/2016/06/vikings_season3_cast.jpg?w=1500&h=768&crop=1',
        status: 'watched',
        genre: ['Ação'],
    },
    {
        id: '0',
        title: 'Vikings',
        sinopse: 'A série é inspirada nas histórias de invasões, comércio e exploração dos Nórdicos da Escandinávia medieval. ... A série se passa no início da era viking, marcada pelo ataque de Lindisfarne, em 793.',
        imgURL: 'https://umpoucodeseries.files.wordpress.com/2016/06/vikings_season3_cast.jpg?w=1500&h=768&crop=1',
        status: 'watched',
        genre: ['Ação'],
    },
    {
        id: '0',
        title: 'Vikings',
        sinopse: 'A série é inspirada nas histórias de invasões, comércio e exploração dos Nórdicos da Escandinávia medieval. ... A série se passa no início da era viking, marcada pelo ataque de Lindisfarne, em 793.',
        imgURL: 'https://umpoucodeseries.files.wordpress.com/2016/06/vikings_season3_cast.jpg?w=1500&h=768&crop=1',
        status: 'watched',
        genre: ['Ação'],
    },
    {
        id: '0',
        title: 'Vikings',
        sinopse: 'A série é inspirada nas histórias de invasões, comércio e exploração dos Nórdicos da Escandinávia medieval. ... A série se passa no início da era viking, marcada pelo ataque de Lindisfarne, em 793.',
        imgURL: 'https://umpoucodeseries.files.wordpress.com/2016/06/vikings_season3_cast.jpg?w=1500&h=768&crop=1',
        status: 'watched',
        genre: ['Ação'],
    },
    {
        id: '0',
        title: 'Vikings',
        sinopse: 'A série é inspirada nas histórias de invasões, comércio e exploração dos Nórdicos da Escandinávia medieval. ... A série se passa no início da era viking, marcada pelo ataque de Lindisfarne, em 793.',
        imgURL: 'https://umpoucodeseries.files.wordpress.com/2016/06/vikings_season3_cast.jpg?w=1500&h=768&crop=1',
        status: 'watched',
        genre: ['Ação'],
    },
];

export default series;